import type { AirportRestaurant } from '@boarding/domain';

/**
 * Curated restaurant data for top US airports.
 * In production, this is supplemented by live APIs (Yelp, Google Places, airport feeds).
 */
export const diningSeeds: AirportRestaurant[] = [
  // ─── JFK ──────────────────────────────────────────────────────────
  { id: 'jfk-1', airport_iata: 'JFK', name: 'Shake Shack', terminal: 'T4', concourse: null, near_gates: ['B20', 'B22', 'B24'], cuisine_type: 'American', price_range: '$$', hours: { open: '06:00', close: '22:00' }, is_open_now: true, rating: 4.2, review_count: 1250, image_url: null, menu_url: null, accepts_mobile_order: true, estimated_wait_minutes: 10, dietary_options: [], walk_time_from_security_minutes: 5, description: 'Classic burgers, fries, and shakes from the NYC icon.' },
  { id: 'jfk-2', airport_iata: 'JFK', name: 'Deep Blue Sushi', terminal: 'T5', concourse: null, near_gates: ['1', '3', '5'], cuisine_type: 'Japanese', price_range: '$$$', hours: { open: '07:00', close: '21:00' }, is_open_now: true, rating: 4.0, review_count: 340, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 15, dietary_options: ['gluten_free'], walk_time_from_security_minutes: 3, description: 'Fresh sushi and Japanese specialties.' },
  { id: 'jfk-3', airport_iata: 'JFK', name: 'Dunkin\'', terminal: 'T4', concourse: null, near_gates: ['B30', 'B32'], cuisine_type: 'Coffee', price_range: '$', hours: { open: '04:30', close: '23:00' }, is_open_now: true, rating: 3.5, review_count: 800, image_url: null, menu_url: null, accepts_mobile_order: true, estimated_wait_minutes: 5, dietary_options: [], walk_time_from_security_minutes: 2, description: 'Coffee and donuts.' },

  // ─── LAX ──────────────────────────────────────────────────────────
  { id: 'lax-1', airport_iata: 'LAX', name: 'Lemonade', terminal: 'T4', concourse: null, near_gates: ['40', '42', '44'], cuisine_type: 'California', price_range: '$$', hours: { open: '06:00', close: '22:00' }, is_open_now: true, rating: 4.1, review_count: 560, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 8, dietary_options: ['vegetarian', 'vegan', 'gluten_free'], walk_time_from_security_minutes: 4, description: 'Seasonal California-inspired marketplace cuisine.' },
  { id: 'lax-2', airport_iata: 'LAX', name: 'In-N-Out (nearby)', terminal: 'TBIT', concourse: null, near_gates: ['130', '132'], cuisine_type: 'Fast Food', price_range: '$', hours: { open: '10:30', close: '01:00' }, is_open_now: true, rating: 4.5, review_count: 2100, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 15, dietary_options: [], walk_time_from_security_minutes: 8, description: 'West coast burger chain. Located near the airport.' },
  { id: 'lax-3', airport_iata: 'LAX', name: 'Starbucks', terminal: 'T5', concourse: null, near_gates: ['50', '52'], cuisine_type: 'Coffee', price_range: '$$', hours: { open: '04:00', close: '22:00' }, is_open_now: true, rating: 3.8, review_count: 720, image_url: null, menu_url: null, accepts_mobile_order: true, estimated_wait_minutes: 5, dietary_options: ['vegetarian'], walk_time_from_security_minutes: 2, description: 'Coffee, pastries, and light bites.' },

  // ─── ORD ──────────────────────────────────────────────────────────
  { id: 'ord-1', airport_iata: 'ORD', name: 'Tortas Frontera', terminal: 'T3', concourse: 'K', near_gates: ['K1', 'K3', 'K5'], cuisine_type: 'Mexican', price_range: '$$', hours: { open: '05:30', close: '21:00' }, is_open_now: true, rating: 4.5, review_count: 1800, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 12, dietary_options: ['vegetarian', 'gluten_free'], walk_time_from_security_minutes: 5, description: 'Rick Bayless\'s acclaimed tortas and guacamole.' },
  { id: 'ord-2', airport_iata: 'ORD', name: 'Garrett Popcorn', terminal: 'T1', concourse: 'B', near_gates: ['B1', 'B3'], cuisine_type: 'Snacks', price_range: '$', hours: { open: '06:00', close: '21:00' }, is_open_now: true, rating: 4.3, review_count: 950, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 5, dietary_options: ['gluten_free'], walk_time_from_security_minutes: 3, description: 'Chicago\'s famous CaramelCrisp and CheeseCorn blend.' },
  { id: 'ord-3', airport_iata: 'ORD', name: 'Publican Tavern', terminal: 'T2', concourse: 'E', near_gates: ['E1', 'E3'], cuisine_type: 'American', price_range: '$$$', hours: { open: '11:00', close: '21:00' }, is_open_now: true, rating: 4.2, review_count: 420, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 18, dietary_options: [], walk_time_from_security_minutes: 6, description: 'Farm-to-table gastropub from the celebrated Chicago restaurant.' },

  // ─── ATL ──────────────────────────────────────────────────────────
  { id: 'atl-1', airport_iata: 'ATL', name: 'Chick-fil-A', terminal: 'A', concourse: 'A', near_gates: ['A1', 'A3', 'A5'], cuisine_type: 'Fast Food', price_range: '$', hours: { open: '05:00', close: '22:00' }, is_open_now: true, rating: 4.3, review_count: 3200, image_url: null, menu_url: null, accepts_mobile_order: true, estimated_wait_minutes: 8, dietary_options: [], walk_time_from_security_minutes: 2, description: 'Chicken sandwiches and nuggets. Atlanta\'s own.' },
  { id: 'atl-2', airport_iata: 'ATL', name: 'One Flew South', terminal: 'E', concourse: 'E', near_gates: ['E14', 'E16'], cuisine_type: 'Southern Fusion', price_range: '$$$', hours: { open: '11:00', close: '22:00' }, is_open_now: true, rating: 4.6, review_count: 890, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 20, dietary_options: ['gluten_free'], walk_time_from_security_minutes: 10, description: 'Award-winning upscale Southern-Asian fusion. Best airport restaurant in the US.' },
  { id: 'atl-3', airport_iata: 'ATL', name: 'Grindhouse Killer Burgers', terminal: 'B', concourse: 'B', near_gates: ['B10', 'B12'], cuisine_type: 'American', price_range: '$$', hours: { open: '06:00', close: '21:00' }, is_open_now: true, rating: 4.1, review_count: 650, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 10, dietary_options: [], walk_time_from_security_minutes: 5, description: 'Handcrafted burgers and hand-cut fries.' },

  // ─── DEN ──────────────────────────────────────────────────────────
  { id: 'den-1', airport_iata: 'DEN', name: 'Root Down DIA', terminal: 'C', concourse: 'C', near_gates: ['C30', 'C32'], cuisine_type: 'American', price_range: '$$$', hours: { open: '07:00', close: '21:00' }, is_open_now: true, rating: 4.4, review_count: 720, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 15, dietary_options: ['vegetarian', 'vegan', 'gluten_free'], walk_time_from_security_minutes: 6, description: 'Locally sourced, creative American cuisine from the Denver favorite.' },
  { id: 'den-2', airport_iata: 'DEN', name: 'New Belgium Hub', terminal: 'B', concourse: 'B', near_gates: ['B40', 'B42'], cuisine_type: 'Bar', price_range: '$$', hours: { open: '06:00', close: '22:00' }, is_open_now: true, rating: 4.0, review_count: 480, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 8, dietary_options: [], walk_time_from_security_minutes: 4, description: 'Colorado craft beers and pub food.' },

  // ─── SFO ──────────────────────────────────────────────────────────
  { id: 'sfo-1', airport_iata: 'SFO', name: 'Cat Cora\'s Kitchen', terminal: 'T2', concourse: null, near_gates: ['D1', 'D3'], cuisine_type: 'Mediterranean', price_range: '$$$', hours: { open: '06:00', close: '22:00' }, is_open_now: true, rating: 4.0, review_count: 380, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 12, dietary_options: ['vegetarian', 'gluten_free'], walk_time_from_security_minutes: 4, description: 'Iron Chef Cat Cora\'s Mediterranean-inspired dishes.' },
  { id: 'sfo-2', airport_iata: 'SFO', name: 'Napa Farms Market', terminal: 'T2', concourse: null, near_gates: ['D8', 'D10'], cuisine_type: 'Market', price_range: '$$', hours: { open: '05:00', close: '22:00' }, is_open_now: true, rating: 4.3, review_count: 920, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 5, dietary_options: ['vegetarian', 'vegan'], walk_time_from_security_minutes: 3, description: 'Local artisan market with wine, cheese, sandwiches, and snacks.' },

  // ─── SEA ──────────────────────────────────────────────────────────
  { id: 'sea-1', airport_iata: 'SEA', name: 'Beecher\'s Handmade Cheese', terminal: 'C', concourse: 'C', near_gates: ['C1', 'C3'], cuisine_type: 'American', price_range: '$$', hours: { open: '05:00', close: '22:00' }, is_open_now: true, rating: 4.5, review_count: 1400, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 10, dietary_options: ['vegetarian'], walk_time_from_security_minutes: 3, description: 'Award-winning mac & cheese and artisan cheese from Pike Place Market.' },
  { id: 'sea-2', airport_iata: 'SEA', name: 'Starbucks Reserve', terminal: 'N', concourse: 'N', near_gates: ['N1', 'N3'], cuisine_type: 'Coffee', price_range: '$$', hours: { open: '04:30', close: '22:00' }, is_open_now: true, rating: 4.2, review_count: 650, image_url: null, menu_url: null, accepts_mobile_order: true, estimated_wait_minutes: 5, dietary_options: [], walk_time_from_security_minutes: 2, description: 'Premium Starbucks experience with reserve roasts. Seattle\'s hometown coffee.' },
  { id: 'sea-3', airport_iata: 'SEA', name: 'Bambuza Vietnam Kitchen', terminal: 'A', concourse: 'A', near_gates: ['A8', 'A10'], cuisine_type: 'Vietnamese', price_range: '$$', hours: { open: '06:00', close: '21:00' }, is_open_now: true, rating: 4.1, review_count: 390, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 12, dietary_options: ['gluten_free'], walk_time_from_security_minutes: 5, description: 'Vietnamese pho, banh mi, and fresh rolls.' },

  // ─── DFW ──────────────────────────────────────────────────────────
  { id: 'dfw-1', airport_iata: 'DFW', name: 'Pappadeaux Seafood', terminal: 'A', concourse: null, near_gates: ['A20', 'A22'], cuisine_type: 'Seafood', price_range: '$$$', hours: { open: '11:00', close: '21:00' }, is_open_now: true, rating: 4.3, review_count: 520, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 20, dietary_options: ['gluten_free'], walk_time_from_security_minutes: 6, description: 'Gulf Coast seafood and Cajun specialties.' },
  { id: 'dfw-2', airport_iata: 'DFW', name: 'Whataburger', terminal: 'C', concourse: null, near_gates: ['C10', 'C12'], cuisine_type: 'Fast Food', price_range: '$', hours: { open: '05:00', close: '23:00' }, is_open_now: true, rating: 4.1, review_count: 1100, image_url: null, menu_url: null, accepts_mobile_order: true, estimated_wait_minutes: 8, dietary_options: [], walk_time_from_security_minutes: 3, description: 'Texas burger chain. Open late.' },

  // ─── MIA ──────────────────────────────────────────────────────────
  { id: 'mia-1', airport_iata: 'MIA', name: 'La Carreta', terminal: 'J', concourse: 'J', near_gates: ['J1', 'J3'], cuisine_type: 'Cuban', price_range: '$$', hours: { open: '06:00', close: '22:00' }, is_open_now: true, rating: 4.2, review_count: 890, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 12, dietary_options: [], walk_time_from_security_minutes: 4, description: 'Authentic Cuban cuisine — a Miami institution since 1976.' },
  { id: 'mia-2', airport_iata: 'MIA', name: 'Vino Volo', terminal: 'D', concourse: 'D', near_gates: ['D20', 'D22'], cuisine_type: 'Wine Bar', price_range: '$$$', hours: { open: '09:00', close: '21:00' }, is_open_now: true, rating: 4.0, review_count: 310, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 5, dietary_options: ['vegetarian'], walk_time_from_security_minutes: 5, description: 'Curated wine flights and small plates.' },

  // ─── BOS ──────────────────────────────────────────────────────────
  { id: 'bos-1', airport_iata: 'BOS', name: 'Legal Sea Foods', terminal: 'B', concourse: null, near_gates: ['B30', 'B32'], cuisine_type: 'Seafood', price_range: '$$$', hours: { open: '06:00', close: '22:00' }, is_open_now: true, rating: 4.3, review_count: 1050, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 15, dietary_options: ['gluten_free'], walk_time_from_security_minutes: 5, description: 'New England seafood institution. Famous clam chowder.' },
  { id: 'bos-2', airport_iata: 'BOS', name: 'Dunkin\'', terminal: 'A', concourse: null, near_gates: ['A10', 'A12'], cuisine_type: 'Coffee', price_range: '$', hours: { open: '04:00', close: '23:00' }, is_open_now: true, rating: 3.6, review_count: 1500, image_url: null, menu_url: null, accepts_mobile_order: true, estimated_wait_minutes: 5, dietary_options: [], walk_time_from_security_minutes: 2, description: 'Boston\'s favorite coffee chain. It\'s practically required.' },

  // ─── MCO ──────────────────────────────────────────────────────────
  { id: 'mco-1', airport_iata: 'MCO', name: 'Cask & Larder', terminal: 'B', concourse: null, near_gates: ['70', '72'], cuisine_type: 'Southern', price_range: '$$$', hours: { open: '06:00', close: '22:00' }, is_open_now: true, rating: 4.2, review_count: 440, image_url: null, menu_url: null, accepts_mobile_order: false, estimated_wait_minutes: 15, dietary_options: ['vegetarian'], walk_time_from_security_minutes: 6, description: 'Southern-inspired craft kitchen and brewery.' },
  { id: 'mco-2', airport_iata: 'MCO', name: 'Starbucks', terminal: 'A', concourse: null, near_gates: ['30', '32'], cuisine_type: 'Coffee', price_range: '$$', hours: { open: '04:30', close: '22:00' }, is_open_now: true, rating: 3.8, review_count: 680, image_url: null, menu_url: null, accepts_mobile_order: true, estimated_wait_minutes: 5, dietary_options: ['vegetarian'], walk_time_from_security_minutes: 2, description: 'Your reliable coffee stop.' },
];
